services:
  - type: web
    name: sms-spam-flask
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT src.flask_app:app
    envVars:
      - key: MODEL_PATH
        value: models/spam_model.joblib
      - key: VECTORIZER_PATH
        value: models/vectorizer.joblib
      - key: METRICS_PATH
        value: models/metrics.json

